version: "3.7"

services:
    python2:
        image: python:${PYTHON2_VERSION}
        command: python main.py
        volumes:
            - ./python2:${DOCKER_SRC_DIR}
        working_dir: ${DOCKER_SRC_DIR}
    python3:
        image: python:${PYTHON3_VERSION}
        command: python main.py
        volumes:
            - ./python3:${DOCKER_SRC_DIR}
        working_dir: ${DOCKER_SRC_DIR}
    python-project:
        build:
            context: ./${PROJECT_NAME}
        command: python main.py
        image: ${PROJECT_NAME}
        volumes:
            - ./${PROJECT_NAME}:${DOCKER_SRC_DIR}
        working_dir: ${DOCKER_SRC_DIR}
    python-project-dev:
        build:
            context: ./${PROJECT_NAME}
            dockerfile: Dockerfile.dev
        volumes:
            - ./${PROJECT_NAME}:${DOCKER_SRC_DIR}
            - ${HOME}/.vscode-server:/home/${USER_NAME}/.vscode-server
        working_dir: ${DOCKER_SRC_DIR}
        tty: true
        ports:
            - "${LOCAL_SSH_PORT}:22"
        depends_on:
            - python-project
        hostname: "${PROJECT_NAME}-dev"
