FROM python-app

# 一般ユーザ名を設定
ENV USER_NAME=dev
ENV USER_ID=1000
ENV GROUP_ID=1000
ENV PASSWD="dev123"

# developerユーザを作成し、sudoを使用できるようにする
RUN apt-get update
RUN apt-get install -y sudo vim
RUN groupadd -g $GROUP_ID $USER_NAME
RUN useradd -d /home/$USER_NAME -m -s /bin/bash -u $USER_ID -g $GROUP_ID $USER_NAME
RUN passwd -d ${USER_NAME}
RUN echo "${USER_NAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/${USER_NAME}
RUN echo "export PS1=\"[\u@\h \W]\\$ \"" >> /home/$USER_NAME/.bashrc

# SSHサーバを立てる
# https://qiita.com/YumaInaura/items/1d5c18a9e55484ccad89
# https://qiita.com/kanosawa/items/07e26edb19c86091fa48
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
#RUN sed -E -i 's/#PasswordAuthentication .+/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -E -i 's/#PermitEmptyPasswords .+/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
RUN sed -E -i 's/UsePAM .+/UsePAM no/' /etc/ssh/sshd_config
EXPOSE 22

WORKDIR /usr/src/app
CMD ["/usr/sbin/sshd", "-D"]
# 起動はrootユーザでなければ失敗する。
